version: '3.7'

services:
  mega:
    image: rudi2e/megacmd:latest
    build:
      context: .
    container_name: mega
    restart: unless-stopped
    user: 1000:1000
    network_mode: bridge
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - ./home:/home/user # Your home folder
      - /home/user/private:/mnt/private # Sync folder
